steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:latest'
  - '--tag=asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
  - '.'
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
- 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
