steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - '--tag=asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
  - '.'
  waitFor: ['-']
  
images:
- 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
- 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
